language: python

cache: pip

python:
  - 2.7
  - 3.5
  - 3.6

env:
  global:
    - TEST_DIR=/tmp/_gpdvega/

before_install:
  - pip install pip --upgrade;

install:
  - pip install -e .[dev];

script:
  - flake8 ./;
  - python -m pytest --pyargs --doctest-modules -v --cov gpdvega --cov-report term-missing;
after_success:
  - coveralls